<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@page import="java.sql.*,java.util.*"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Order Product</title>
<link rel="stylesheet" href="css/book.css">
<link rel="stylesheet" href="css/nav.css">

</head>
<body>
<script>
	var today = new Date();
	var dd = today.getDate();

	var mm = today.getMonth()+1; 
	var yyyy = today.getFullYear();
	if(dd<10) 
	{
	    dd='0'+dd;
	} 

	if(mm<10) 
	{
	    mm='0'+mm;
	} 
	today = dd+'-'+mm+'-'+yyyy;
	
	

	</script>

<div class="nav">
  <ul>
    <li class="logo">E-Agro</li>
    <li class="account"><a href="account.jsp">Account</a></li>
    <li><a href="SellProduct.jsp">Sell Product</a></li>
    
    <li><a href="Products.jsp">Order Product</a></li>
    <li><a class="active" href="AboutUs.html">About Us</a></li>
    <li><a href="index.jsp">Home</a></li>
  </ul>
  </div>
<section class="profile" id="profile1">
<%

try{    	String product_id=request.getParameter("id");
            String quantity=request.getParameter("quantity");
            String add=request.getParameter("address");


	   
      Class.forName("com.mysql.jdbc.Driver");
      Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/e-agro", "root", "8756");
      Statement st=conn.createStatement();
      ResultSet rs=st.executeQuery("select * from products where products_id='"+product_id+"'");
	    while(rs.next())
	    {
	    	int q=Integer.parseInt(quantity);
	    	int q2=Integer.parseInt(rs.getString("products_stock"));
	    	if(q2>=q){
	    	
	    %>
	    


<div class="userprofile">
  <h2>Bill</h2>
  <p class="point"><b>Product Id:</b><%=rs.getString("products_id")%> </p>
      <p class="point"><b>Product Name:</b><%=rs.getString("products_name")%> </p>
      <p class="point"><b>Product Type:</b><%=rs.getString("products_type")%></p>
      <p class="point"><b>Product Price:</b><%=rs.getString("products_price")%></p>
      <%int price=Integer.parseInt(rs.getString("products_price"));
       
        int bill=price*q;
         %>
         <p class="point"><b>Order Quantity:</b><%=quantity%></p>
         <p class="point"><b>Total Bill:</b><%=bill%></p>
   <!-- <form action="payment.jsp" method="post">-->
  <!--   <form action="" method="post">-->
        <input type="text" name="p_id" value="<%=rs.getString("products_id")%>" style="display:none">
        <input type="text" name="quantity" value="<%=quantity%>" style="display:none">
        <input type="text" name="add" value="<%=add%>" style="display:none">
        <input type="text" name="bill" value="<%=bill%>" style="display:none">
       <!--   <input type="submit" id="submit"name="submit" value="Pay Bill">-->
       <div class="form-element">
    <!--<button name="pay_btn">Pay Now</button>-->
    
<%String api_key="rzp_test_Inr1Lu5WMZuWiy";//gsdeveloper%>

<form action="payment2.jsp" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<% out.print(api_key);%>"  // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<% out.print(bill*100);%>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="100"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Now"
    data-name="E-Agro"
    data-description="Make Happy order!!"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="vishal"
    data-prefill.email="email"
    data-prefill.contact="7083847727"
    data-theme.color="#F37254"
></script>
        <input type="text" name="p_id" value="<%=rs.getString("products_id")%>" style="display:none">
        <input type="text" name="quantity" value="<%=quantity%>" style="display:none">
        <input type="text" name="add" value="<%=add%>" style="display:none">
        <input type="text" name="bill" value="<%=bill%>" style="display:none">
        <input type="text" name="date" value="<script>document.write(today);</script>" style="display:none">
<input type="hidden" custom="Hidden Element" name="hidden">
</form>



  </div>
       
     
  <!--   </form> -->  
      
</div><% }else{
	response.sendRedirect("ErrorQuntity.html");
}
	    	}
}catch(Exception e){
	    	out.print(e);
	    }  
%>
</section>
</body>
</html>